### ISSUE TITLE
Constructor token option not used

### ISSUE THREAD

**Issue by brendonv** [Nike-Inc/cerberus-node-client#24]
The `token` on the constructor options param is never set.

**Comment by fieldju** [comment]
I think [this](https://github.com/Nike-Inc/cerberus-node-client/blob/d2447523cd73d49a80bebfbeca7caa255e2134cc/index.js#L173) is where it used to get the token.

I am in favor of just removing the option, but I am curious to see what @kyeotic thinks, should we bring this feature back or remove it from the jsdocs?

**Comment by fieldju** [comment]
Side note, I recommend using STS auth for local development and not using the token option or the env var option.

If you have [gimme-aws-creds](https://github.com/Nike-Inc/gimme-aws-creds) set up, its as simple as running gimme-aws-creds then starting your app and just letting it run like it does in production and adding your teams IAM Role to the SDB instead.

**Comment by kyeotic** [comment]
Since its the only way to inject a token into a specific client I think we should put it back in. Its designed for testing, and some tests run in parallel, so `process.env` isn't a great solution.
