### ISSUE TITLE
Client Version HTTP Header

### ISSUE THREAD

**Issue by tlisonbee** [Nike-Inc/cerberus-node-client#6]
Cerberus client should self report their name and version via HTTP header with all requests to Cerberus. This is a feature request against all Cerberus clients. This feature will be helpful in understanding:
- What clients are being used in a particular Cerberus environment
- If a bug exists in a certain client version, is that client still being used by applications

The format for this header is similar to the User-Agent string. In fact, we considered using the User-Agent Header but thought using a custom header will make some reporting easier.

Specification:
HTTP Header name: 'X-Cerberus-Client'
Example value: 'CerberusJavaClient/1.4.0'

**Comment by tyrsius** [comment]
@tlisonbee  Added under `v1.1.0`, [published here](https://github.com/Nike-Inc/cerberus-node-client/releases/tag/v1.1.0)
